### PR TITLE
fix: alembic only run migrations if required

### PR DESCRIPTION
**Pull request by fynnos**
with this PR the migration script assumes that the version is up-to-date if no version is set in the database (e.g. fresh installs). 
**Thus, older instances will not be migrated anymore!** There is no way to differentiate between an old DB and a fresh install.

Before merging thus, we should update all running semi-prod instances; e.g. HCDS demo.

### CODE REVIEW

**Comment by floschne** [comment]
@fynnos @bigabig can this get merged ?

**Comment by floschne** [comment]
@fynnos @bigabig  push

**Comment by raffomania** [comment]
According to @bigabig , Fynn is absent until february :smile:

**Comment by floschne** [comment]
Oh no :D So in that case: @bigabig , do you think we can merge this?

**Pull request closed without merging**
