### PR TITLE
Add github action for updating openapi spec

### PR DESCRIPTION
**Pull request by raffomania**

### CODE REVIEW

**Review by bigabig — COMMENTED** [review]
The proposed GitHub action is nice to have the frontend's API client up-to-date with the backend.

However, if the backend API changes (drastically), so will the API client in the frontend. This will cause errors in the frontend, unnoticed by the developer.

To catch these errors, I suggest building the frontend with 'npm run build' (in this action?). This process will fail in case of newly introduced errors.

**Review by floschne — APPROVED** [review]
I like. Also, its cleaner with the RAY_ENABLED instead of adding this variable to sys for the tests.

**Comment by raffomania** [comment]
Sadly, the current openapi spec causes our frontend to break. I've talked to @bigabig and he'd say it will most likely be fixed in his next PR.

**Review by floschne — CHANGES_REQUESTED** [review]
Please rebase so that we can merge :-)

**Comment by raffomania** [comment]
Rebased :)

**Pull request merged**
