### PR TITLE
Add simple ownership authorization

### PR DESCRIPTION
**Pull request by raffomania**
This adds authorization checks using a new dependency: `is_authorized`. For now, this is only applied to the project endpoints. If you're happy with how it works, I'd like to create a second PR for extending this mechanism to the rest of the backend.

It's separated so the big repetitive changes are in their own commits to make reviewing easier :)

### CODE REVIEW

**Comment by floschne** [comment]
@raffomania this need a rebase on `mwp_v1`

**Review by floschne — CHANGES_REQUESTED** [review]
please rebase on `mwp_v1`

**Comment by floschne** [comment]
@raffomania what is the state here?

**Comment by raffomania** [comment]
@floschne This is complete, tested and can be merged. It implements complete ownership authorization for all endpoints in `api/endpoints/project.py`. To keep the PR scope manageable, I'd like to implement authorization for other endpoints in a follow-up PR.

**Pull request merged**
