### PR TITLE
Add ruff linter & formatter

### PR DESCRIPTION
**Pull request by raffomania**
[ruff](https://docs.astral.sh/ruff/) is a very fast and feature rich linter and formatter. Using it instead of black, flake8 and isort simplifies the project configuration and makes the pre-commit hook faster :)

The ruff VSCode extension can automatically fix many linting errors, I'd highly recommend it.

### CODE REVIEW

**Comment by bigabig** [comment]
I am also using ruff. With this my local linter / formatter and the formatter used by pre-commit are in sync.

**Comment by floschne** [comment]
I'm also very fine with ruff since I also use it in other projects :) 
please adjust the tests

**Review by floschne — APPROVED** [review]

**Review by floschne — CHANGES_REQUESTED** [review]
Thanks! Ruff is great! Please adjust the tests / CI so that they run through :)

**Comment by raffomania** [comment]
**This will remove all unused imports**. Are we fine with that or should I remove the auto-fix for that?

**Review by floschne — APPROVED** [review]

**Pull request merged**
